### ISSUE TITLE
JSON generation

### ISSUE THREAD

**Issue by duzenko** [synw/geojson#11]
How do I generate a new geojson from e.g. Google Map polygons?

**Comment by synw** [comment]
Create a `GeoJsonFeatureCollection` object with all it's children and then use

```dart
String serializedJson = myFeatureCollection.serialize();
```

I should add a section in the readme to document that

**Comment by duzenko** [comment]
Am I stupid or GeoJsonPolygon.serializeFeature is broken? Local variable `geoSeries` eclipses member field geoSeries in that method resulting in `_buildGeoJsonFeature` been always fed an empty list.

**Comment by synw** [comment]
Pr merged, closing

**Comment by duzenko** [comment]
Sorry, what about a `pub.dev` update?
