### ISSUE TITLE
Custom feature properties?

### ISSUE THREAD

**Issue by duzenko** [synw/geojson#15]
I need to send some decoration info for my polygons (e.g. color).
How can I do this with GeoJsonFeatureCollection.serialize?
![image](https://user-images.githubusercontent.com/1481807/68755520-48929c80-0611-11ea-8f4e-bebba521c39d.png)

**Comment by duzenko** [comment]
Found it
```
      feature.properties = {
        'color': ColorToHex(area.color),
        'label': area.label.toMap(),
      };
```

**Comment by duzenko** [comment]
Blocked by https://github.com/synw/geojson/pull/16

**Comment by duzenko** [comment]
I can see that my PR got merged but I haven't had the time to test this properly yet. Gimme a few days.

**Comment by synw** [comment]
Ok, let me know when you think that the serialization features are usable, then we will document them. Oh and btw please run `flutter analyze` on your commits: we have pretty strict linting rules
