### ISSUE TITLE
Flutter: search from an asset file

### ISSUE THREAD

**Issue by alfaruqrizqi18** [synw/geojson#17]
Hi, I'm little confused.
I've located my in assets folder and add to pubspec.yaml, when I try to load in it. I got error "The file does not exist". How to solve it? Thank you
![image](https://user-images.githubusercontent.com/43517239/69948263-e3e8a480-1521-11ea-9ab0-abf54f9cdbe8.png)

**Comment by synw** [comment]
I guess you are using this with Flutter. Afaik you can not load a file directly from the asset folder. So you have two options here:

- Copy the file to a path where the app can access it, like the documents directory
- Load the file content as a string and use `search`:

```dart
final data = await rootBundle.loadString('assets/countries.geojson');
geo.search(data, GeoJsonQuery(//..));
```

**Comment by alfaruqrizqi18** [comment]
ok, let me try this way

**Comment by alfaruqrizqi18** [comment]
Hai @synw can u help me to process my geojson file? Can u give some example how to do it?
this is my geojson file http://bumi.id/mapbox/batas_zona_perairan.geojson and I want to show it to my flutter_map. Thank u

**Comment by synw** [comment]
> I want to show it to my flutter_map

Easy: you can use my [map controller](https://github.com/synw/map_controller) package that can draw on a map from geojson. Check this example: https://github.com/synw/map_controller/blob/master/example/lib/geojson.dart

**Comment by alfaruqrizqi18** [comment]
But, I still don't know how to get the coordinates :D

**Comment by alfaruqrizqi18** [comment]
this is my current code 
![image](https://user-images.githubusercontent.com/43517239/70017459-bcdbb280-15b5-11ea-9e18-105a53253dc0.png)

and this is message what I got
![image](https://user-images.githubusercontent.com/43517239/70017543-f9a7a980-15b5-11ea-98e6-43d08c4f34a2.png)

**Comment by synw** [comment]
Use the geojson objects

```dart
GeoJsonMultiLine.lines.geoSerie.geoPoints
```

**Comment by alfaruqrizqi18** [comment]
where should I put those code?

**Comment by synw** [comment]
Dude, please do a bit of research by yourself, I will not code your program for you. There are plenty of examples to refer to for reading data
