### ISSUE TITLE
Geojson data from api  

### ISSUE THREAD

**Issue by adnanefouam** [synw/geojson#21]
i have multiple adresses from api with coordinates and i want to display their geojson data on the map like this
<img width="1680" alt="Screen Shot 2020-05-12 at 07 51 23" src="https://user-images.githubusercontent.com/59290932/81669061-27323200-9435-11ea-8e9e-bbd222ce7ef9.png">

- import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong/latlong.dart';
import 'package:promy_app/utilities/style.dart';
import 'package:geojson/geojson.dart';

import 'dart:async';
import 'package:map_controller/map_controller.dart';
class Mapboxtest extends StatefulWidget {

  final double lat;
  final double lon;
  final Object data;

   Mapboxtest ({ Key key,  @required this.lat,@required this.lon,this.data }): super(key: key);
@override
  _MapboxtestState createState() => new _MapboxtestState();
}

class _MapboxtestState extends State<Mapboxtest> {

  MapController mapController;
  StatefulMapController statefulMapController;
  StreamSubscription<StatefulMapControllerStateChange> sub;
  final lines = <Polyline>[];
  Future<void> parseAndDrawAssetsOnMap() async {
    final geo = GeoJson();
    geo.processedLines.listen((GeoJsonLine line) {
      setState(() => lines.add(Polyline(
        borderColor: Colors.red,
          strokeWidth: 4.0, color: primarycolor, points: line.geoSerie.toLatLng())));
    });
    geo.endSignal.listen((_) => geo.dispose());
    final data = widget.data;
    await geo.parse(data, verbose: true);

  }

  @override
  void initState() {
    mapController = MapController();
    statefulMapController = StatefulMapController(mapController: mapController);
    statefulMapController.onReady.then((_) => parseAndDrawAssetsOnMap());
    sub = statefulMapController.changeFeed.listen((change) => setState(() {}));
    super.initState();
  }
  @override
  Widget build(BuildContext context) {

    return Scaffold(
        body: Stack(
          children: <Widget>[
            FlutterMap(
                options:
                    MapOptions(
                      center: LatLng( widget.lon , widget.lat), zoom: 15,
                minZoom: 3.0,
               maxZoom: 20.0,
                      interactive: true, ),
                layers: [

              TileLayerOptions(
                  urlTemplate:
                  'https://api.mapbox.com/styles/v1/adnanefouham/cka1mwzas5g9k1iou3qn3odle/tiles/256/{z}/{x}/{y}@2x?access_token=TOKEN_KEY',              additionalOptions: {
                    'accessToken':
                        'TOKEN_KEY',
                    'id': 'mapbox.mapbox-stretts-v8',
                  }),

              MarkerLayerOptions(markers: [
                Marker(
                    width: 45.0,
                    height: 45.0,
                    point: LatLng(widget.lon , widget.lat),
                    builder: (context) => Container(
                          child: IconButton(
                            icon: Icon(Icons.location_on),
                            color: primarycolor,
                            iconSize: 45.0,
                            onPressed: () {
                              parseAndDrawAssetsOnMap();
                              print('Marker tapped');
                            },
                          ),
                        ))
              ]),
                  PolylineLayerOptions(
                    polylines: statefulMapController.lines,
                  ),
            ]),

          ],
        ));
  }
}

**Comment by adnanefouam** [comment]
the geojson  package do the job  with flutter map

**Comment by kingdj** [comment]
Hey I'm trying to load geojson multipolygon into the map but can't do that as it throws various catches being LatLong usage polygon duplication and heatmap.
I am using Google map flutter, & geojson package from dart repo.
