### ISSUE TITLE
Polygon & Point namespace confused by geojson

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [synw/geojson#4]
With the latest update I can't use Polygon from the poly package and neither Point from dart.math because geojson contains both of those Classes and thus confuses the namespace. This is my example script which worked fine before, but now don't. Could you make geojsons internal classes which are not part of the api private?

```
import 'dart:ffi';
import 'dart:io';
import 'package:geojson/geojson.dart';
import 'package:poly/poly.dart';

void main() async {
  polygons();
}

bool polygonContains(Polygon poli, Point target){
  return poli.contains(target.x, target.y);
}

void polygons() async {
  final file = File("ecorregiones.geojson");
  final geoSeries = await featuresFromGeoJsonFile(file);
  Point target = Point(-59.797841999254999, -19.72303808501668);
  List<Point> pointList = [];
  List<List<Point>> pointSeries = [];

  for (final geoSerie in geoSeries) {
    //print("${geoSerie.name}: ${geoSerie.geoPoints.length} geopoints");

    pointList = [];
    for (final geoPoint in geoSerie.geoPoints){
      double x = geoPoint.latitude;
      double y = geoPoint.longitude;
      Point p = Point(x, y);
      pointList.add(p);
    }

    Polygon poli = Polygon(pointList);
    bool contains = polygonContains(poli, target);
    if(contains){
      print('YES! $target is contained in ${geoSerie.name}.');
    }
    else print('nope!');
  }

}
```

**Comment by synw** [comment]
I see. About your suggested solution I can not make the data models private because they are sometimes useful for type casts like `final geom = feature.geometry as MultiPolygon`

There are two potential solutions:

- Change the api and prefix the classes like `GeoJsonPoint`
- Recommend import in custom namespaces in case of name clashes, like `import 'package:geojson/geojson.dart as geojson'`

What would be better?

**Comment by Karlheinzniebuhr** [comment]
I used `geojson.featuresFromGeoJsonFile()` but in order to use the below function
```
bool polygonContains(Polygon poli, Point target){
  return poli.contains(target.x, target.y);
}
```
I have to use the poly library. Does the geojson package have functionality to verify if one polygon is contained in another one? For instance imagine if someone presses on a certain point of a map, and I want to verify what features are associated with that area.

**Comment by synw** [comment]
What about this:

```
import 'package:poly/poly.dart' as poly;

bool polygonContains(poly.Polygon poli, poly.Point target){
  return poli.contains(target.x, target.y);
}
```
Would it be ok? Btw thanks for mentioning the Poly lib, I did not know it and it looks good. I use the [Geodesy](https://github.com/wingkwong/geodesy) package for detecting point in a polygon. Making calculations on the data is not in the scope of this library and yes we should rely on external packages to do it.

**Comment by synw** [comment]
In the 0.5.0 release I prefixed all the classes by `GeoJson` : @Karlheinzniebuhr the names clash with other libraries like Poly and Flutter map. You were right, there was too many name clashes: it's more convenient to prefix than to use namespaces

If you already have code and want to take your time for the transition use the 0.4.0 release.

**Comment by Karlheinzniebuhr** [comment]
Ok great, thank you, as soon as I get to that project I'll test it.
