### ISSUE TITLE
[BUG] Crash if name property is missing 

### ISSUE THREAD

**Issue by sanekyy** [synw/geojson#5]

**Comment by synw** [comment]
Did you use the last version 0.2.1? In the example there is one with the name property not provided and it does not crash. Could you please provide some code to reproduce? This would help to circumvent the problem

**Comment by sanekyy** [comment]
![image](https://user-images.githubusercontent.com/18647037/62142427-0447ee80-b2f7-11e9-96cb-e16be32ec45d.png)

**Comment by synw** [comment]
I misunderstood your issue and was thinking you talked about the `nameProperty` parameter but reading your code I think it is about when the json does not contain properties. This has been fixed in the new 0.2.2 : please try with this version and let me know if everything is ok

**Comment by sanekyy** [comment]
Everything is ok.
