### ISSUE TITLE
[FEATURE] return future from featuresFromGeoJson

### ISSUE THREAD

**Issue by sanekyy** [synw/geojson#6]
Execution time of featuresFromGeoJson may be very long if json will be too big.
Try to split internal body of featuresFromGeoJson to little futures to avoid freezing of main Isolate and also return Furute from featuresFromGeoJson in general.

**Comment by synw** [comment]
Good idea. I'll try to split the processing to different isolates for each feature. I have a package that can help doing the job: https://github.com/synw/iso .I'll make experiments and try with big files.

**Comment by synw** [comment]
I tried to spawn an isolate for each feature but it is not efficient: isolates are definitely not as cheap as goroutines. So I just made the parser to run in it's own isolate. I did not have time to test with big files yet. Feel free to try out this new feature on master for big files if you have the time

**Comment by sanekyy** [comment]
Okay, I'll try

**Comment by synw** [comment]
I tested with big files and it works fine: there are new examples using Flutter to draw data on a map and one of them uses a 24 Mo file with polygons for all the countries in the world: it only takes a few seconds to parse in the isolate, leaving the main thread alone.

**Comment by synw** [comment]
Related note: a reactive api has been added in 0.4.0: the features can not be retrieved as soon as they are parsed: this is useful for big files.

**Comment by sanekyy** [comment]
Great.
Thx.
