### ISSUE TITLE
Synchronous parsing

### ISSUE THREAD

**Issue by neokree** [synw/geojson#7]
When dealing with a large geoJson having a way to fetch each feature after it's parsing is good, but when you deal on a very little geoJson (with only one feature, for instance) it's an overkill. 

Can you add a way to parse the geoJson synchronously?

**Comment by synw** [comment]
You can await the functions:

```dart
final features = await featuresFromGeoJson(data);
```

or the with class:

```dart
final geojson = GeoJson();
await geojson.parse(data);
final features = geojson.features;
// or to get just the polygons for example
final polygons = geojson.polygons;
```

The data is still parsed in an isolate but you don't have to listen to streams.

**Comment by neokree** [comment]
Yeah I know that I could `await` it, but I was looking for a way for not doing it, since the data to be parsed in my case is so small that doing in the main thread is not a problem.

**Comment by synw** [comment]
I think that parsing the data in the main thread is not a good idea. Even if it is small it may cause ui problems like a short circular progress indicator freeze: parsing is cpu intensive. Is the few milliseconds overhead  of spawning an isolate really a problem?

**Comment by neokree** [comment]
It is not the few milliseconds the problem , but the async logic for parsing in my case (I am parsing the geojson in a `@computed` variable of MobX). Anyway, after thinking about it it is not a good reason to do it, since the wrongly use of the synchonous parse could cause problems for other library users, which could just use it because it is more "simpler". 

Closing
